# Generated by Django 3.0 on 2019-12-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameservice', '0002_auto_20191210_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gameservice.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedata',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gameservice.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gameservice.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
