# Generated by Django 3.0 on 2019-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservice', '0005_auto_20191229_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
